version: '3.3'
services:
  db:
    image: postgres:13.0-alpine
    volumes:
      - /var/lib/postgresql/data/
    env_file:
      - ./.env

  backend:

    container_name: app
    build:
      context: ../backend
      dockerfile: ../backend/Dockerfile
    volumes:
      - ../static/:/app/static/
      - ../media/:/app/media/recipes/
    depends_on:
      - db
    env_file:
      - ./.env
    restart: always

  frontend:

    container_name: front
    build:
      context: ../frontend
      dockerfile: Dockerfile
    volumes:
      - ../frontend/:/app/result_build/
    depends_on:
      - db

  nginx:

    build:
      context: ../nginx
      dockerfile: Dockerfile
    ports:
      - "9090:80"
    volumes:
      - ../static/:/var/html/static/
      - ../media/:/var/html/media/recipes/
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ../frontend/build:/usr/share/nginx/html/
      - ../docs/:/usr/share/nginx/html/api/docs/
    depends_on:
      - backend
      - frontend
    restart: always

volumes:

  postgres_data:
  static_value:
  media_value:
